/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication24.view;

import java.util.ArrayList;
import java.util.List;
import javaapplication24.model.HopThit;
import javaapplication24.model.LoaiThit;
import javaapplication24.model.Thit;
import javaapplication24.service.impl.HopThitService;
import javaapplication24.service.impl.HopThitViewService;
import javaapplication24.service.impl.LoaiThitService;
import javaapplication24.service.impl.LoaiThitViewService;
import javaapplication24.service.impl.ThitService;
import javaapplication24.viewmodel.HopThitViewModel;
import javaapplication24.viewmodel.LoaiThitViewModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SanPhamView extends javax.swing.JPanel {
    ThitService ts = new ThitService();
    LoaiThitService lts = new LoaiThitService();
    HopThitService hts = new HopThitService();
    LoaiThitViewService ltvs = new LoaiThitViewService();
    HopThitViewService htvs = new HopThitViewService();
    List<Thit> listt = new ArrayList<>();
    List<HopThit> listht = new ArrayList<>();
    List<LoaiThit> listlt = new ArrayList<>();
    List<HopThitViewModel> listhtv = new ArrayList<>();
    List<LoaiThitViewModel> listltv = new ArrayList<>();
    DefaultTableModel dtmt = new DefaultTableModel();
    DefaultTableModel dtmlt = new DefaultTableModel();
    DefaultTableModel dtmht = new DefaultTableModel();
    DefaultComboBoxModel dcmt = new DefaultComboBoxModel();
    DefaultComboBoxModel dcmlt = new DefaultComboBoxModel();
    public SanPhamView() {
        initComponents();
        dtmt = (DefaultTableModel) this.tblThit.getModel();
        dtmlt = (DefaultTableModel) this.tblLoaiThit.getModel();
        dtmht = (DefaultTableModel) this.tblHopThit.getModel();
        dcmt = (DefaultComboBoxModel) this.cboThit.getModel();
        dcmlt = (DefaultComboBoxModel) this.cboLoaiThit.getModel();
        listt = ts.getList();
        listlt = lts.getList();
        listht = hts.getList();
        listltv = ltvs.getList();
        listhtv = htvs.getList();
        showDataDcmt(listt);
        showDataDcmlt(listlt);
        showDataDtmt(listt);
        showDaataDtmltv(listltv);
        showDataDtmhtv(listhtv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTrongLuong = new javax.swing.JTextField();
        txtNgaySanXuat = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHopThit = new javax.swing.JTable();
        btnAddHopThit = new javax.swing.JButton();
        btnUpdateHopthit = new javax.swing.JButton();
        cboLoaiThit = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenLoaiThit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboThit = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtGiaTheoKg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHSD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiThit = new javax.swing.JTable();
        btnAddLoaiThit = new javax.swing.JButton();
        btnUpdateLoaithit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMoTaLoaiThit = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThit = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtMota = new javax.swing.JTextField();

        jLabel7.setText("LoaiThit");

        jLabel8.setText("trọng lượng");

        jLabel9.setText("Giá");

        jLabel10.setText("Số lượng");

        jLabel11.setText("Ngày sản xuất");

        tblHopThit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "loaiThit", "trọng Lượng", "Giá", "Số lượng", "Ngày sản xuất"
            }
        ));
        tblHopThit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHopThitMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHopThit);

        btnAddHopThit.setText("thêm");
        btnAddHopThit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddHopThitMouseClicked(evt);
            }
        });

        btnUpdateHopthit.setText("Sửa");
        btnUpdateHopthit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateHopthitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboLoaiThit, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtTrongLuong)
                            .addComponent(txtGia)
                            .addComponent(txtSoLuong))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addGap(30, 30, 30)
                        .addComponent(txtNgaySanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddHopThit)
                            .addComponent(btnUpdateHopthit)))
                    .addComponent(jScrollPane3))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgaySanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnAddHopThit)
                    .addComponent(cboLoaiThit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTrongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateHopthit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HopThit", jPanel1);

        jLabel3.setText("Tên");

        jLabel4.setText("Thit");

        jLabel5.setText("GiaTheoKg");

        jLabel6.setText("HSD(Ngay)");

        tblLoaiThit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên", "VitriThịt", "GiáTheoKg", "HSD", "MoTa"
            }
        ));
        tblLoaiThit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiThitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiThit);

        btnAddLoaiThit.setText("Thêm");
        btnAddLoaiThit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddLoaiThitMouseClicked(evt);
            }
        });

        btnUpdateLoaithit.setText("Sửa");
        btnUpdateLoaithit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateLoaithitMouseClicked(evt);
            }
        });

        jLabel12.setText("Mota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(txtTenLoaiThit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtGiaTheoKg))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(43, 43, 43)
                                    .addComponent(cboThit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHSD, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtMoTaLoaiThit))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateLoaithit)
                            .addComponent(btnAddLoaiThit))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenLoaiThit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtHSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddLoaiThit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboThit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateLoaithit)
                    .addComponent(jLabel12)
                    .addComponent(txtMoTaLoaiThit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaTheoKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LoaiThit", jPanel2);

        jLabel1.setText("Ten");

        jLabel2.setText("Mota");

        tblThit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdThit", "Ten", "Mota"
            }
        ));
        tblThit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThitMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThit);

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTen)
                            .addComponent(txtMota, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnSua))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSua))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thit", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        if(kiemTraDuLieuThit()){
            Thit t = new Thit(txtTen.getText(),txtMota.getText());
            if(ts.add(t)){
                JOptionPane.showMessageDialog(this,"Them thanh cong");
                listt = ts.getList();
                showDataDcmt(listt);
            }else {
                JOptionPane.showMessageDialog(this, "them that bai");
            }
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        int row = tblThit.getSelectedRow();
        if(row>=0&&row<listt.size()||kiemTraDuLieuThit()){
            String id = listt.get(row).getIdThit();
            Thit t = new Thit(id,txtTen.getText(),txtMota.getText());
            if(ts.update(t)){
                JOptionPane.showMessageDialog(this,"Update thanh cong");
                listt = ts.getList();
                showDataDcmt(listt);
            }else {
                JOptionPane.showMessageDialog(this, "Update that bai");
            }
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void tblThitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThitMouseClicked
        // TODO add your handling code here:
        int row = tblThit.getSelectedRow();
        if(row>=0&&row<listt.size()){
            Thit t = listt.get(row);
            txtTen.setText(t.getTen());
            txtMota.setText(t.getMoTa());
        }
    }//GEN-LAST:event_tblThitMouseClicked

    private void btnAddLoaiThitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLoaiThitMouseClicked
        // TODO add your handling code here:
        if(kiemTraDuLieuLoaithit()){
            String id = listt.get(cboThit.getSelectedIndex()).getIdThit();
            LoaiThit lt = new LoaiThit(id,txtTenLoaiThit.getText(),Integer.parseInt(txtGiaTheoKg.getText()),Integer.parseInt(txtHSD.getText()),txtMoTaLoaiThit.getText());
            if(lts.add(lt)){
                JOptionPane.showMessageDialog(this,"add thanh cong");
                listlt = lts.getList();
                showDataDcmlt(listlt);
            }else {
                JOptionPane.showMessageDialog(this,"add that bai");
            }
        }
    }//GEN-LAST:event_btnAddLoaiThitMouseClicked

    private void btnUpdateLoaithitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateLoaithitMouseClicked
        // TODO add your handling code here:
        int row = tblLoaiThit.getSelectedRow();
        if(row>=0&&row<listlt.size()&&kiemTraDuLieuLoaithit()){
            String id = listt.get(cboThit.getSelectedIndex()).getIdThit();
            LoaiThit lt = new LoaiThit(listlt.get(row).getIdLoaiThit(),id,txtTenLoaiThit.getText(),Integer.parseInt(txtGiaTheoKg.getText()),Integer.parseInt(txtHSD.getText()),txtMoTaLoaiThit.getText());
            if(lts.update(lt)){
                JOptionPane.showMessageDialog(this,"update thanh cong");
                listlt = lts.getList();
                showDataDcmlt(listlt);
            }else {
                JOptionPane.showMessageDialog(this,"update that bai");
            }
        }
    }//GEN-LAST:event_btnUpdateLoaithitMouseClicked

    private void tblLoaiThitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiThitMouseClicked
        // TODO add your handling code here:
        int row = tblLoaiThit.getSelectedRow();
        if(row>=0&&row<listlt.size()){
            LoaiThitViewModel ltvm = listltv.get(row);
            txtTenLoaiThit.setText(ltvm.getTen());
            txtGiaTheoKg.setText(String.valueOf(ltvm.getGiaTheoKg()));
            txtHSD.setText(String.valueOf(ltvm.getHSD()));
            cboThit.setSelectedItem(ltvm.getThit());
        }
    }//GEN-LAST:event_tblLoaiThitMouseClicked

    private void tblHopThitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopThitMouseClicked
        // TODO add your handling code here:
        int row = tblHopThit.getSelectedRow();
        if(row>=0&&row<listhtv.size()){
            HopThitViewModel htv = listhtv.get(row);
            cboLoaiThit.setSelectedItem(htv.getLoaiThit());
            txtGia.setText(String.valueOf(htv.getGia()));
            txtTrongLuong.setText(String.valueOf(htv.getTrongLuong()));
            txtSoLuong.setText(String.valueOf(htv.getSoLuong()));
            txtNgaySanXuat.setText(htv.getNgaySanXuat());
        }
    }//GEN-LAST:event_tblHopThitMouseClicked

    private void btnAddHopThitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddHopThitMouseClicked
        // TODO add your handling code here:
        if(kiemTraDuLieuHopThit()){
            String id = listlt.get(cboLoaiThit.getSelectedIndex()).getIdLoaiThit();
            HopThit ht = new HopThit(id,Double.parseDouble(txtTrongLuong.getText()) ,Double.parseDouble(txtGia.getText()),Integer.parseInt(txtSoLuong.getText()),txtNgaySanXuat.getText());
            if(hts.add(ht)){
                JOptionPane.showMessageDialog(this,"add thanh cong");
                listhtv = htvs.getList();
                showDataDtmhtv(listhtv);
            }else {
                JOptionPane.showMessageDialog(this,"add that bai");
            }
        }
    }//GEN-LAST:event_btnAddHopThitMouseClicked

    private void btnUpdateHopthitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateHopthitMouseClicked
        // TODO add your handling code here:
        int row = tblHopThit.getSelectedRow();
        if(row>=0&&row<listhtv.size()&&kiemTraDuLieuHopThit()){
            HopThit ht = new HopThit(listht.get(row).getIdHopThit(),listlt.get(cboLoaiThit.getSelectedIndex()).getIdLoaiThit() ,Double.parseDouble(txtTrongLuong.getText()),Double.parseDouble(txtGia.getText()),Integer.parseInt(txtSoLuong.getText()),txtNgaySanXuat.getText());
            if(hts.update(ht)){
                JOptionPane.showMessageDialog(this,"update thanh cong");
                listhtv = htvs.getList();
                showDataDtmhtv(listhtv);
            }else {
                JOptionPane.showMessageDialog(this,"update that bai");
            }
        }
    }//GEN-LAST:event_btnUpdateHopthitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHopThit;
    private javax.swing.JButton btnAddLoaiThit;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdateHopthit;
    private javax.swing.JButton btnUpdateLoaithit;
    private javax.swing.JComboBox<String> cboLoaiThit;
    private javax.swing.JComboBox<String> cboThit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblHopThit;
    private javax.swing.JTable tblLoaiThit;
    private javax.swing.JTable tblThit;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtGiaTheoKg;
    private javax.swing.JTextField txtHSD;
    private javax.swing.JTextField txtMoTaLoaiThit;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtNgaySanXuat;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenLoaiThit;
    private javax.swing.JTextField txtTrongLuong;
    // End of variables declaration//GEN-END:variables

    private void showDataDcmt(List<Thit> listt) {
        for(Thit t:listt){
            dcmt.addElement(t.getTen());
        }
    }

    private void showDataDcmlt(List<LoaiThit> listlt) {
        for(LoaiThit lt:listlt){
            dcmlt.addElement(lt.getTen());
        }
    }

    private boolean kiemTraDuLieuThit() {
        if(txtTen.getText().trim().isEmpty()||txtMota.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Nhap du du lieu");
            return false;
        }
        return false;
    }

    private boolean kiemTraDuLieuLoaithit() {
        if(txtTenLoaiThit.getText().trim().isEmpty()||txtGiaTheoKg.getText().trim().isEmpty()||txtHSD.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Nhap du du lieu");
            return false;
        }else if(kiemTraKieuInt(txtHSD.getText())){
            JOptionPane.showMessageDialog(this,"Nhap du du lieu");
            return false;
        }
        return true;
    }

    private boolean kiemTraKieuInt(String text) {
        int t ;
        try {
            t = Integer.parseInt(text);
        } catch (Exception e) {
            e.printStackTrace(System.out);
            return true;
        }
        return t<=0;
    }

    private void showDataDtmt(List<Thit> listt) {
        dtmt.setRowCount(0);
        for(Thit t:listt){
            dtmt.addRow(new Object[]{t.getIdThit(),t.getTen(),t.getMoTa()});
        }
    }

    private void showDaataDtmltv(List<LoaiThitViewModel> listltv) {
        dtmlt.setRowCount(0);
        for(LoaiThitViewModel ltv:listltv){
            dtmlt.addRow(new Object[]{ltv.getTen(),ltv.getThit(),ltv.getGiaTheoKg(),ltv.getHSD(),ltv.getMoTa()});
        }
    }

    private void showDataDtmhtv(List<HopThitViewModel> listhtv) {
        dtmht.setRowCount(0);
        for(HopThitViewModel htv : listhtv){
            dtmht.addRow(new Object[]{htv.getLoaiThit(),htv.getTrongLuong(),htv.getGia(),htv.getSoLuong(),htv.getNgaySanXuat()});
        }
    }

    private boolean kiemTraDuLieuHopThit() {
        if(txtTrongLuong.getText().trim().isEmpty()||txtGia.getText().trim().isEmpty()||txtSoLuong.getText().trim().isEmpty()||txtNgaySanXuat.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Nhap du du lieu");
            return false;
        }else if(kiemTraKieuInt(txtSoLuong.getText())||kiemTraKieuDouble(txtGia.getText())||kiemTraKieuDouble(txtTrongLuong.getText())){
            JOptionPane.showMessageDialog(this,"Nhap du lieu so");
            return false;
        }
        return true;
    }

    private boolean kiemTraKieuDouble(String text) {
        double t ;
        try {
            t = Double.parseDouble(text);
        } catch (Exception e) {
            e.printStackTrace(System.out);
            return true;
        }
        return t<=0;
    }
}
