/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication24.view;

import java.util.ArrayList;
import java.util.List;
import javaapplication24.model.Voucher;
import javaapplication24.model.VoucherChiTiet;
import javaapplication24.service.VoucherChiTietService;
import javaapplication24.service.VoucherService;
import javaapplication24.service.impl.VoucherChiTietServiceImpl;
import javaapplication24.service.impl.VoucherServiceImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VoucherView extends javax.swing.JPanel {

    VoucherService vs = new VoucherServiceImpl();
    VoucherChiTietService vcts = new VoucherChiTietServiceImpl();
    List<Voucher> listvoucher = new ArrayList<>();
    DefaultTableModel dtmv = new DefaultTableModel();
    List<VoucherChiTiet> listvct = new ArrayList<>();
    DefaultTableModel dtmvct = new DefaultTableModel();
    public VoucherView() {
        initComponents();
        dtmv = (DefaultTableModel) this.tblVoucher.getModel();
        dtmvct = (DefaultTableModel) this.tblVoucherChiTiet.getModel();
        listvct = vcts.getList();
        listvoucher = vs.getList();
        showDataTableVoucher(listvoucher);
        showDataTableVoucherChiTiet(listvct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtHSD = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnHien = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMucGiaGioiHan = new javax.swing.JTextField();
        txtDkNhan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgayKetThuc = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtGiatri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVoucherChiTiet = new javax.swing.JTable();
        txtHoaDonCanTim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnTimKiemHD = new javax.swing.JButton();

        btnTimKiem.setText("Search");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        jLabel4.setText("DkNhan");

        btnHien.setText("Hien");
        btnHien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienMouseClicked(evt);
            }
        });

        jLabel6.setText("MucGiaGioiHan");

        jLabel7.setText("NgayKetThuc");

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        jLabel5.setText("Tên");

        jLabel1.setText("Loại");

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo %", "Theo $" }));

        jLabel2.setText("Giá trị");

        txtGiatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiatriActionPerformed(evt);
            }
        });

        jLabel8.setText("TenTimKiem");

        jLabel3.setText("HSD(ngày)");

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ten", "Loai", "Gia tri", "HSD", "DKNhan", "MucGiaGioiHan", "NgayKetThuc"
            }
        ));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucher);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(67, 67, 67)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiatri, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHSD, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMucGiaGioiHan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDkNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnHien)
                            .addComponent(btnTimKiem))
                        .addContainerGap(109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDkNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMucGiaGioiHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGiatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTenTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Voucher", jPanel1);

        tblVoucherChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idVoucherChiTiet", "idVoucher", "idKhachHang", "NgayBatDau", "Tình trạng", "idHoaDon"
            }
        ));
        tblVoucherChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVoucherChiTiet);

        jLabel9.setText("IdHoaDonCanTim");

        btnTimKiemHD.setText("Tìm kiếm");
        btnTimKiemHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemHDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28)
                        .addComponent(txtHoaDonCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(btnTimKiemHD))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoaDonCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnTimKiemHD))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("VoucherChitiet", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
        if (txtTenTimKiem.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhap ten tim kiem");
        } else {
            List<Voucher> list = new ArrayList<>();
            for (Voucher vou : listvoucher) {
                if (vou.getTen().equalsIgnoreCase(txtTenTimKiem.getText().trim())) {
                    list.add(vou);
                }
            }
            showDataTableVoucher(list);
        }
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnHienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienMouseClicked
        // TODO add your handling code here:
        showDataTableVoucher(listvoucher);
    }//GEN-LAST:event_btnHienMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        if (kiemTraDuLieu()) {
            Voucher vou = new Voucher(txtTen.getText(), (byte) (cboLoai.getSelectedIndex()), Integer.parseInt(txtGiatri.getText()), Integer.parseInt(txtHSD.getText()), Integer.parseInt(txtDkNhan.getText()), Integer.parseInt(txtMucGiaGioiHan.getText()), txtNgayKetThuc.getText());
            if (vs.add(vou)) {
                JOptionPane.showMessageDialog(this, "add thanh cong");
                listvoucher = vs.getList();
                showDataTableVoucher(listvoucher);
            } else {
                JOptionPane.showMessageDialog(this, "add that bai");
            }
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        int row = tblVoucher.getSelectedRow();
        if (row >= 0 && row < listvoucher.size() && kiemTraDuLieu()) {
            String id = listvoucher.get(row).getId();
            Voucher vou = new Voucher(id, txtTen.getText(), (byte) (cboLoai.getSelectedItem().toString().equalsIgnoreCase("Theo %") ? 0 : 1), Integer.parseInt(txtGiatri.getText()), Integer.parseInt(txtHSD.getText()), Integer.parseInt(txtDkNhan.getText()), Integer.parseInt(txtMucGiaGioiHan.getText()), txtNgayKetThuc.getText());
            if (vs.update(vou)) {
                JOptionPane.showMessageDialog(this, "update thanh cong");
                listvoucher = vs.getList();
                showDataTableVoucher(listvoucher);
            } else {
                JOptionPane.showMessageDialog(this, "update that bai");
            }
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void txtGiatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiatriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiatriActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        // TODO add your handling code here:
        int row = tblVoucher.getSelectedRow();
        if (row >= 0 && row < listvoucher.size()) {
            Voucher vou = listvoucher.get(row);
            txtTen.setText(vou.getTen());
            txtGiatri.setText(String.valueOf(vou.getGiaTri()));
            txtHSD.setText(String.valueOf(vou.getHsd()));
            cboLoai.setSelectedItem(vou.getLoai() == 0 ? "Theo %" : "Theo $");
            txtDkNhan.setText(String.valueOf(vou.getDkNhan()));
            txtMucGiaGioiHan.setText(String.valueOf(vou.getMucGiaGioiHan()));
            txtNgayKetThuc.setText(vou.getNgayKetThuc());
        }
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void tblVoucherChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherChiTietMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVoucherChiTietMouseClicked

    private void btnTimKiemHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemHDMouseClicked
        // TODO add your handling code here:
        if(txtHoaDonCanTim.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Nhap idHoaDonCantim");
        }else {
            List<VoucherChiTiet> listsearch = new ArrayList<>();
            for(VoucherChiTiet vct :listvct){
                if(txtHoaDonCanTim.getText().trim().equalsIgnoreCase(vct.getIdHoaDon())){
                    listsearch.add(vct);
                }
            }
            showDataTableVoucherChiTiet(listsearch);
        }
    }//GEN-LAST:event_btnTimKiemHDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHien;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiemHD;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTable tblVoucherChiTiet;
    private javax.swing.JTextField txtDkNhan;
    private javax.swing.JTextField txtGiatri;
    private javax.swing.JTextField txtHSD;
    private javax.swing.JTextField txtHoaDonCanTim;
    private javax.swing.JTextField txtMucGiaGioiHan;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenTimKiem;
    // End of variables declaration//GEN-END:variables

    private void showDataTableVoucher(List<Voucher> listvoucher) {
        dtmv.setRowCount(0);
        for (Voucher vou : listvoucher) {
            dtmv.addRow(new Object[]{vou.getTen(), vou.getLoai() == 0 ? "Theo %" : "Theo $", vou.getGiaTri(), vou.getHsd(), vou.getDkNhan(), vou.getMucGiaGioiHan(), vou.getNgayKetThuc()});
        }
    }

    private boolean kiemTraDuLieu() {
        if (txtTen.getText().trim().isEmpty() || txtGiatri.getText().trim().isEmpty() || txtHSD.getText().trim().isEmpty() || txtDkNhan.getText().trim().isEmpty() || txtGiatri.getText().trim().isEmpty() || txtMucGiaGioiHan.getText().trim().isEmpty() || txtNgayKetThuc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhap du du lieu");
            return false;
        } else if (kiemTraKieuInt(txtGiatri.getText()) || kiemTraKieuInt(txtHSD.getText()) || kiemTraKieuInt(txtDkNhan.getText()) || kiemTraKieuInt(txtMucGiaGioiHan.getText())) {
            JOptionPane.showMessageDialog(this, "Nhap du lieu so");
            return false;
        }
        return true;
    }

    private boolean kiemTraKieuInt(String text) {
        int t;
        try {
            t = Integer.parseInt(text);
        } catch (NumberFormatException e) {
            return true;
        }
        return t <= 0;
    }

    private void showDataTableVoucherChiTiet(List<VoucherChiTiet> listvct) {
        dtmvct.setRowCount(0);
        for(VoucherChiTiet vct :listvct){
            dtmvct.addRow(new Object[]{vct.getIdVoucherChiTiet(),vct.getIdVoucher(),vct.getIdKhachHang(),vct.getNgayBatDau(),getTrangThai(vct.getTrangThai()),vct.getIdHoaDon()});
        }
    }

    private String getTrangThai(byte trangThai) {
        return switch (trangThai) {
            case 0 -> "Chua su dung";
            case 1 -> "Da su dung";
            case 2 -> "het han";
            default -> null;
        };
    }
}
